name: build-and-bundle

# Controls when the workflow will run
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-bundle:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Print file count
        if: ${{ env.ACT }}
        run: find | wc -l

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Print file count
        if: ${{ env.ACT }}
        run: find | wc -l

      - name: Run install
        uses: borales/actions-yarn@v4.2.0 # suffers from <https://github.com/nektos/act/issues/1600>
        with:
          cmd: install # will run `yarn install` command

      - name: Check for and report any vulnerabilities
        # report any high and critical vulnerabilities
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: electronegativity --severity high # will run `yarn electronegativity` script to return "high" or above severity vulnerabilities

      - name: Print file count
        if: ${{ env.ACT }}
        run: find | wc -l

      - name: Print file count
        if: ${{ env.ACT }}
        run: find | wc -l

      - name: Build the package
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build # will run `yarn build` script

      - name: Print file count
        if: ${{ env.ACT }}
        run: find | wc -l

#      - name: Package /dist with electron-builder
#        # https://www.electron.build/

      - name: Package the bundle
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: package # will run `yarn package` script

      - name: Print file count
        if: ${{ env.ACT }}
        run: find | wc -l

      - name: List 'package' directory
        if: ${{ env.ACT }}
        run: ls -halF package

      - name: Bundle the package
        uses: vimtor/action-zip@v1
        with:
          files: package/
          dest: electron-secure-defaults-app.zip

      - name: List 'electron-secure-defaults-app.zip' contents
        if: ${{ env.ACT }}
        run: unzip -l electron-secure-defaults-app.zip

      - name: Print file count
        if: ${{ env.ACT }}
        run: find | wc -l

      - uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: electron-secure-defaults-artifact
          path: ${{ github.workspace }}/electron-secure-defaults-app.zip
          if-no-files-found: error

      - name: Print file count
        if: ${{ env.ACT }}
        run: find | wc -l

      # it seems to be unreasonably convoluted to retrieve the artifact URL, so I'll omit it in the output:
      # https://github.com/actions/upload-artifact/issues/50
      # https://github.com/orgs/community/discussions/51403
      - name: Print build results
        id: notification_content
        run: |
          NOTIFICATION_CONTENT=$(cat << EOF

            Here is a report on the status of build #${{ steps.checkout.outputs.build.number }}:
            * Status: 
            * Artifacts: 
            * Warnings:
            * Errors:

            You can find the full details here:j
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EOF
          )
          echo "::set-output name=content::$NOTIFICATION_CONTENT"

      - name: Notify build results
        # include:
        # - a URL that points to the build
        # - the status of the build
        # - any other relevant information
        run: echo "${{ steps.notification_content.outputs.content }}"

#        uses: actions/email@v2
#        with:
#          to: 5051062+fevrin@users.noreply.github.com
#          subject: "Build #${{ steps.checkout.outputs.build.number }} report"
#          body: echo "${{ steps.notification_content.outputs.content }}"
